### ISSUE TITLE
summation_delivered_value is ZERO sometimes

### ISSUE THREAD

**Issue by stevel032** [gtdiehl/eagle200_reader#6]
I use this module with Home Assistant, and it's a great piece of code, thank you guys!

Unfortunately I'm getting an occasional ZERO value, several times in a day. See screen shot. I wonder if the module itself can detect such cases and return an error condition rather than a zero value as if it is a good value.

![Screen Shot 2021-04-20 at 11 11 51 PM](https://user-images.githubusercontent.com/55261196/115505108-d2469080-a22d-11eb-92b1-079dc7c87e4b.png)

**Comment by nicholashead** [comment]
@stevel032 I'm running across this too. It seems like there should be a check to not accept 0 values like you said.

**Comment by nicholashead** [comment]
@gtdiehl I'm a developer, but am not totally familiar with Python - was going to try and take a go at fixing this, but looking at the code - is the "None" being returned from eagle200_reader - and then the HA integration is reading that in as 0? Basically trying to figure out where this issue should be fixed - in this repo, or in the HA integration?

**Comment by rccoleman** [comment]
The code says this:

```
            summation_received = self._get_value(device_attributes, 'zigbee:CurrentSummationReceived')
            # Eagle-200 has a bug, sometimes the Value for Summation Received will have the incorrect
            # decimal place.  If six zeros to the right of the decimal point are found than it'll assume
            # the value is incorrect and return None
            if summation_received[summation_received.find('.')+1:] != "000000":
                self.summation_received_value = summation_received
            else:
                self.summation_received_value = None
```

Same for summation_delivered.

**Comment by nicholashead** [comment]
Right, I'm guessing that the "None" (null?) is being interpreted as 0 on the HA side, and the HA component should instead discard the result?

**Comment by stevel032** [comment]
"None" in Python is indeed like "Null" in C/C++ and JavaScript, and typically has to be interpreted as 0 when forced to convert/cast to a number type. The best thing to do is to perhaps simply report a failure? or even reporting the last good number is better than returning None/0, which messes things up.

**Comment by gtdiehl** [comment]
Closing issue. Home Assistant is no longer using the ```eagle200_reader``` library
